<?php

/**
 * Implements hook_permission().
 */
function etype_jailbirds_importer_permission() {
  return array(
    'administer json import' => array(
      'title' => t('Administer JSON Import'),
    )
  );
}

/**
 * add import and admin urls
 * @return array
 */
function etype_jailbirds_importer_menu() {

  $items = array();

  $items['import_jailbird_json'] = array(
    'title' => 'Import OK Jailbirds JSON',
    'description' => 'OK Jailbirds JSON Importer',
    'page callback' => 'etype_jailbirds_importer_import',
    'access arguments' => array('administer json import'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'etype_jailbirds_importer.import.inc'
  );

  return $items;
}
