<?php

/**
 * Implements hook_permission().
 */
function etype_jailbirds_permission()
{
    return array(
        'administer json import' => array(
            'title' => t('Administer JSON Import'),
        )
    );
}

/**
 * add import and admin urls
 * @return array
 */
function etype_jailbirds_menu()
{

    $items = array();

    $items['import_jailbird_json'] = array(
        'title' => 'Import OK Jailbirds JSON',
        'description' => 'OK Jailbirds JSON Importer',
        'page callback' => 'etype_jailbirds_import',
        // 'access arguments' => array('administer json import'),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'etype_jailbirds.import.inc'
    );

    return $items;
}


/**
 * Cron Jobs
 * @param $op
 * @param null $job
 * @return mixed
 */
function etype_jailbirds_cronapi($op, $job = NULL)
{
    $items['etype_jailbirds_import_cron'] = array(
        'description' => 'Import content',
        'rule' => '0 7 * * 6',
        'callback' => 'etype_jailbirds_import',
        'file' => 'etype_jailbirds.import.inc'
    );
    return $items;
}
