<?php

/**
 * Implements hook_permission().
 */
function etype_jailbirds_permission() {
  return [
    'administer json import' => [
      'title' => t('Administer JSON Import'),
    ],
  ];
}

/**
 * admin urls
 * @return array
 */
function etype_jailbirds_menu() {

  $items = [];

  $items['import_jailbird_test'] = [
    'title' => 'Import OK Jailbirds JSON',
    'description' => 'OK Jailbirds JSON Importer',
    'page callback' => 'etype_jailbirds_test',
    'access arguments' => ['access content'],
    'type' => MENU_NORMAL_ITEM,
    'file' => 'etype_jailbirds.import.inc',
  ];

  return $items;
}

/**
 * @return array
 */
function etype_jailbirds_views_api() {
  return [
    'api' => 3,
    'path' => drupal_get_path('module', 'etype_jailbirds') . '/includes',
  ];
}
