<?php

/**
 * Implements hook_permission().
 */
function etype_jailbirds_xml_importer_permission() {
  return array(
    'administer xml import' => array(
      'title' => t('Administer XML Import'),
    )
  );
}

/**
 * add import and admin urls
 * @return array
 */
function etype_jailbirds_xml_importer_menu() {

  $items = array();

  $items['import_jailbird_xml'] = array(
    'title' => 'Import OK Jailbirds XML',
    'description' => 'OK Jailbirds XML Importer',
    'page callback' => 'etype_jailbirds_xml_importer_import',
    'access arguments' => array('administer xml import'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'etype_jailbirds_xml_importer.import.inc'
  );

  return $items;
}
